### ISSUE TITLE
Typo or diff in README and Galaxy Publish

### ISSUE THREAD

**Issue by FQ400** [geerlingguy/ansible-role-packer#3]
Hi @geerlingguy 

First things first. Thank you for the ansible role.

The README says in the example playbook `geerlingguy.packer`. The installed role from galaxy works with  `geerlingguy.ansible-role-packer`.

Galaxy: https://galaxy.ansible.com/geerlingguy/ansible-role-packer/

I found a fork where the rename took place.

Fork: https://github.com/gerardorf/ansible-role-packer/commit/73933ab43fac054153e84ba2ad80166b05f880d6

Could it be that the fork was published to galaxy without updating the README?

**Comment by geerlingguy** [comment]
Eek, I'll take a look. Might also be related:

  - https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names
  - https://github.com/ansible/ansible/issues/42989

**Comment by geerlingguy** [comment]
This is fixed: https://galaxy.ansible.com/geerlingguy/packer

Sorry about that!
