### ISSUE TITLE
Possibly better alternative?

### ISSUE THREAD

**Issue by elreydetoda** [geerlingguy/ansible-role-packer#6]
I mentioned how to do the same steps for ansible, but just sub out `packer` instead of `vagrant` here: https://github.com/diodonfrost/ansible-role-vagrant/issues/2#issue-695221164

tldr; https://medium.com/hashicorp-engineering/hashicorp-packaging-is-here-4c6083dee4f6

**Comment by elreydetoda** [comment]
Might not be a better solution till the repos are a little more stable. more info about my issue using the vagrant mechanism for this here: https://github.com/diodonfrost/ansible-role-vagrant/issues/2#issuecomment-697064391

**Comment by elreydetoda** [comment]
bump, so it doesn't go stale.

**Comment by geerlingguy** [comment]
Just glancing at the original comment in this issue... what is being suggested? What is a better alternative to what?

**Comment by elreydetoda** [comment]
So, @HashiCorp has come out with repos that you can use instead of having to specify the full download url for packer.

So, you can just add their keys and repo to your debian or rhel based distros to get their full suite of hashicorp tools by following this [gist](https://gist.github.com/jboero/c6c90c47837a2db0f6ac9095f6c733d0#file-hashicorprepo-sh) ( which is reference in the blog post in the original comment for the issue ), and that way it handles upgrades when a new version comes out as well if you upgrade everything with apt or yum.

The downside is that you can only specify the version of the tool ( packer in this case ) that they have in their repos, instead of being able to specify the version during the url and grab any version they host for that.

So, I was saying it might be a better alternative to add their repo instead of downloading the binary directly.

**Comment by elreydetoda** [comment]
I am guessing you want to close this issue?
